name: annotated_shelf
description: powerful Dart library for generating REST APIs using annotations. With a simple and intuitive interface, you can easily build APIs that are fast, efficient, and easy to use.
version: 0.1.0
homepage: https://github.com/cheogm28/annotated_shelf

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  http: ^0.13.5

dependencies: {json_annotation: ^4.7.0, shelf: ^1.4.0, shelf_multipart: ^1.0.0}
