name: annotated_shelf
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  http: ^0.13.5

dependencies: {json_annotation: 4.7.0, shelf: 1.4.0, shelf_multipart: 1.0.0}
